### PR TITLE
Google Cloud Storage support

### PR DESCRIPTION
**Pull request by yinzara**

### CODE REVIEW

**Comment by dgautsch** [comment]
Thanks for this PR. Things are looking good so far. Can you add unit tests for it?

**Comment by dgautsch** [comment]
Please remove the package-lock.json file as we use yarn-lock for this project. You'll need to reinstall using yarn.

**Comment by yinzara** [comment]
Sure. I'll work on those two changes. Just out of curiosity, is there any reason to continue using Yarn anymore? Everything I've been reading says it's basically been merged into npm.

I'm also going to see about adding Google Auth login support as well as an oauth provider.   We'll see if I'm successful :)

**Comment by yinzara** [comment]
Similar to the 's3' checks that are performed throughout the test tree, I used the present of the "GCS_BUCKET" and "GOOGLE_APPLICATION_CREDENTIALS" environment variables to enable "gcs" tests in all the same places.  If you set both to valid values, and run 'npm test', all tests pass correctly (with my fixes in the last commit).  I'm not sure how we could have them run during integration tests unless we have some kind of GCloud account to use a bucket on.

**Comment by dgautsch** [comment]
> Sure. I'll work on those two changes. Just out of curiosity, is there any reason to continue using Yarn anymore? Everything I've been reading says it's basically been merged into npm.
> 
> I'm also going to see about adding Google Auth login support as well as an oauth provider. We'll see if I'm successful :)

@yinzara yea there isn't really a reason to keep using yarn. I plan on switching over to npm in the future. Just haven't got around to it :)

**Comment by dgautsch** [comment]
> Similar to the 's3' checks that are performed throughout the test tree, I used the present of the "GCS_BUCKET" and "GOOGLE_APPLICATION_CREDENTIALS" environment variables to enable "gcs" tests in all the same places. If you set both to valid values, and run 'npm test', all tests pass correctly (with my fixes in the last commit). I'm not sure how we could have them run during integration tests unless we have some kind of GCloud account to use a bucket on.

I have an s3 account for our unit tests on CircleCI, we may have to setup a GCloud account for these tests as well.

**Pull request merged**
