### PR TITLE
404 fix

### PR DESCRIPTION
**Pull request by twellspring**
Fix for #96 and #97

### CODE REVIEW

**Comment by twellspring** [comment]
FYI - I did a JSON.parse on a javascript object and it did not affect the object.   So if for some reason body starts coming back as an object again this fix should not cause a problem.

**Comment by diervo** [comment]
FYI With this fix deployed, sometimes I'm getting this error, which probably means the code needs some branching logic:
```
SyntaxError: Unexpected token o in JSON at position 1 
Dec 13 17:48:09 lwc-npm app/web.1:      at JSON.parse (<anonymous>) 
Dec 13 17:48:09 lwc-npm app/web.1:      at Object.get (/app/lib/npm.js:54:16) 
Dec 13 17:48:09 lwc-npm app/web.1:      at <anonymous> 
Dec 13 17:48:09 lwc-npm app/web.1:      at process._tickCallback (internal/process/next_tick.js:160:7) 
Dec 13 17:48:11 lwc-npm app/web.1:  logging error with Opbeat: { uuid: 'c8994eec-f6bc-4f05-bccf-f311126e49bc' } 
Dec 13 17:48:11 lwc-npm app/web.1:  SyntaxError: Unexpected token o in JSON at position 1 
Dec 13 17:48:11 lwc-npm app/web.1:      at JSON.parse (<anonymous>) 
Dec 13 17:48:11 lwc-npm app/web.1:      at Object.get (/app/lib/npm.js:54:16) 
Dec 13 17:48:11 lwc-npm app/web.1:      at <anonymous> 
Dec 13 17:48:11 lwc-npm app/web.1:      at process._tickCallback (internal/process/next_tick.js:160:7) 
```

**Comment by diervo** [comment]
I found the root cause. I described it in #99. Basically there is a race condition on the http-call library.
A terrible hack fixes it temporarily here, but the right fix is in the library itself.

```js
pkg = typeof req.body === 'string' ? JSON.parse(req.body): req.body;
```

**Comment by jdxcode** [comment]
I figured out the issue. npm started sending headers where the content type had capital letters in it and http-call saw the content type as unmatching so it thought that it was no longer in json. Fix is going out now.

**Pull request closed without merging**
