### PR TITLE
Converting start script to run with node so it works on windows and u…

### LINKED ISSUE #101: /usr/bin/env: ‘node\r’: No such file or directory
Hey @dgautsch, did you just publish 2.6.0 from a windows machine? 

`bin/npm-register` has been re-encoded with `\r` for line returns and this is causing the error above. There are similar issues across many projects so it seems to be fairly common, and fixed by specifying encoding:

https://github.com/abrahamjagadeesh/npm-module-stats/issues/1
https://github.com/nwjs-community/nw-builder/pull/105

I was able to verify the fix by opening the file and setting line endings to unix `:set ff=unix`.

I also verified that 2.5.5 worked fine.

Quite a strange bug given that file hasn't changed but perhaps you reopened it before publishing 2.6.0?

### PR DESCRIPTION
**Pull request by dgautsch**
@Ianfeather and @jdxcode can you test this out and see if it works on your machines? It should resolve the issues we're having. Fixes #101

### CODE REVIEW

**Comment by Ianfeather** [comment]
Hey @dgautsch 

Can confirm this works for running `npm start` within npm-register. 👍 

It still doesn't fix the issue I have where I'm running `npm-register` directly. I have a container which starts up npm-register directly. In my package.json I have:

```
"scripts": {
    "start": "npm-register --always-https start"
},
```

This will throw the same error as in #101 regardless of the change in this PR. However I can make it work by updating that to:

```
"scripts": {
    "start": "node /node_modules/.bin/npm-register --always-https start"
},
```

Maybe my use case is a strange one? Either way I have a workaround, which people can now find in the issues here, so I don't think this is a huge problem. Still a bit of a mystery to me how it published with different line endings :/

Thanks for your help with this

**Comment by dgautsch** [comment]
Thanks @Ianfeather ! I'm glad we made a little progress. I'm going to clone the repo again and check the line endings and how git is configured and try republishing with this PR.

**Comment by jdxcode** [comment]
@dgautsch this isn't terrible well documented but you need to add a `.cmd` file for it to work on windows where you can install this with `npm install -g npm-register`. Just add a file like this: https://github.com/dxcli/dev/commit/5d0d46f3196599f43124b18617b0d77223415ea0

npm picks up a .cmd file automatically if it matches another bin file. In this case you'll have to replace `run` with `npm-register`.

**Comment by jdxcode** [comment]
@dgautsch this isn't terrible well documented but you need to add a .cmd file for it to work on windows where you can install this with npm install -g npm-register. Just add a file like this:

https://github.com/dxcli/dev/blob/176fa573d8d783f9eb997c46b1d1ab5ac90376ee/bin/run.cmd#L1-L3

npm picks up a .cmd file automatically if it matches another bin file. In this case you'll have to replace run with npm-register.

**Comment by dgautsch** [comment]
Ah, that's good to know. I had no idea @jdxcode. Do you want me to revert this change? Seems it'll work as well.

**Pull request merged**
